name: 自动提交保持常在线

on:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: 发送空提交
        run: |
          git config --local user.email "i@mengze2.cn"
          git config --local user.name "MengZe2l"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push